# Generated by Django 5.2 on 2025-04-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team', models.CharField(choices=[('red', 'Red Team'), ('blue', 'Blue Team')], max_length=5)),
                ('card_type', models.CharField(choices=[('yellow', 'Initial'), ('red', 'Intermediate'), ('black', 'Final'), ('defense', 'Defense')], max_length=10)),
                ('cost', models.IntegerField(default=0)),
                ('sp_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
