# Generated by Django 5.2 on 2025-04-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umpire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('blue_budget', models.IntegerField(default=70)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='umpire.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PlayedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('red', 'Red Team'), ('blue', 'Blue Team')], max_length=5)),
                ('chain_id', models.IntegerField(blank=True, null=True)),
                ('is_flipped', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umpire.card')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='umpire.turn')),
            ],
        ),
    ]
