# Generated by Django 5.2 on 2025-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umpire', '0002_gamesession_turn_playedcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
