# Generated by Django 5.2 on 2025-04-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_seed_initial_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackDefenseMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.attackcard')),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.defensecard')),
            ],
        ),
    ]
