# Generated by Django 5.2 on 2025-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_seed_attack_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackcard',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='defensecard',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
