# Generated by Django 5.2 on 2025-04-08 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_attackcard_name_alter_defensecard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
